# Generated by Django 6.0.1 on 2026-02-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
